FROM microsoft/aspnet:1.0.0-rc1-update1

COPY project.json /app/
WORKDIR /app
RUN ["dnu", "restore"]
COPY . /app

# default to running the container on port 80
ARG SERVER_URLS=http://*:80
ENV SERVER.URLS $SERVER_URLS
EXPOSE 80

ENTRYPOINT ["dnx", "-p", "project.json", "web"]
